---

- name: Turn swap off
  command: swapoff -a

- name: Remove Swap entry from /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: Configure modules for containerd
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    create: yes
    block: |
        overlay
        br_netfilter

- name: Load containerd kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Installing Prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https
    state: present

- name: Configure kubernetes-cri sys params
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
  with_dict: "{{ sysctl_config }}"

- name: Apply sysctl params without reboot
  command: sysctl --system

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Install containerd
  apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: Create a new directory for containerd
  file:
    path: /etc/containerd
    state: directory

- name: Create a containerd configuration file
  shell: containerd config default > /etc/containerd/config.toml

- name: Set the cgroup driver for runc to systemd
  replace:
    path: /etc/containerd/config.toml
    regexp: (SystemdCgroup\s*=\s*)\S+$
    replace: \1true
  notify:
    - Restart containerd

- name: Add Google’s official GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Install Kubernetes Cluster Packages
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Start kubelet
  systemd:
    state: started
    daemon_reload: yes
    name: kubelet
    enabled: yes
