- name: Installing Prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Install docker-compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy configs
  copy:
    src: files/
    dest: /home/{{ ansible_user }}

- name: Copy alertmanager config
  template:
    src: templates/alertmanager.j2
    dest: /home/{{ ansible_user }}/alertmanager/alertmanager.yml

- name: Run container
  command: docker-compose -f docker-compose.yml up -d
