---

- name: Add Helm's official GPG key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add Helm Repository
  apt_repository:
    repo: deb [arch=amd64] https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm

- name: Install Helm
  apt:
    name: helm
    state: present
    update_cache: yes

- name: Add Promtail chart repo
  become_user: "{{ ansible_user }}"
  command: helm repo add grafana https://grafana.github.io/helm-charts

- name: Copy values files
  copy:
    src: files/
    dest: /home/{{ ansible_user }}

- name: Install Promteil
  become_user: "{{ ansible_user }}"
  command: helm install promtail grafana/promtail --values promtail.values.yml
  ignore_errors: yes

- name: Add kube-state-metrics chart repo
  become_user: "{{ ansible_user }}"
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Install kube-state-metrics
  become_user: "{{ ansible_user }}"
  command: helm install kube-state-metrics prometheus-community/kube-state-metrics --values kube-state-metrics.values.yml
  ignore_errors: yes
